### ISSUE TITLE
Autonomous examples with twgl library in CDN

### ISSUE THREAD

**Issue by munrocket** [greggman/twgl.js#112]
CND is faster than github pages as I can see in lighthouse report. And with it we can easily copy and run it on your own machine.  JAMstack is common pattern now.

**Comment by greggman** [comment]
I am not sure what this issue is about. https://twgljs.org is served from a CDN.

<img width="624" alt="screen shot 2019-03-06 at 4 02 45" src="https://user-images.githubusercontent.com/234804/53830046-edf66a80-3fc4-11e9-87e3-dbc8156926f5.png">

**Comment by munrocket** [comment]
We can’t copypaste raw example from github and run it right now. Because all examples with relative resources <srcipt src=“../dist/twgl-full.js”></script> and not working independently without repo.

**Comment by greggman** [comment]
I'm still not sure what you're asking for

Are you asking for the files in the repo to use CDNs? 

That would make it really frustrating to test new versions since all the examples would point to the CDN not the local changed version. It would also make it super frustrating to run locally without internet, something I do often if I'm in some place with a bad connection or on a plane

Are you asking for the files on the site to use CDNs? 

Basically a site generator that converts the files on github with relative urls to use absolute URLs? That's an interesting idea. I wonder though how often people would copy and paste from the running examples. There is no easy way to access the source. Chrome removed the "view source" options. You can go into devtools and maybe copy and paste the page but I doubt people do that. You could curl/wget the page, seems rare. Firefox has a "page source" option so it would be useful there.

Checking around three.js doesn't do this. All of their examples use local relative links. pixi.js doesn't do this. 

I'd certainly consider making a site generator that makes the links use FQDNs and either uses jsfiddle directly or has a link "open in jsfiddle" someday when I have time.
