### ISSUE TITLE
API docs are too slow

### ISSUE THREAD

**Issue by baturinsky** [greggman/twgl.js#140]
It takes 22 second to open one article article even locally. Checked both on Chrome and Firefox.

**Comment by greggman** [comment]
You must have some extension messing things up. The docs are all of 80k compresed. They open in under 2 seconds.

<img width="721" alt="Screen Shot 2019-10-04 at 13 51 49" src="https://user-images.githubusercontent.com/234804/66182037-36d2e680-e6ae-11e9-815b-4a01f22a92a3.png">

Even locally they open fast

<img width="724" alt="Screen Shot 2019-10-04 at 13 56 22" src="https://user-images.githubusercontent.com/234804/66182152-d3958400-e6ae-11e9-92d6-df346912b60b.png">

Maybe you're using python's default simple server to serve them? [Python's simplehttpserver has known issues at being slow](https://stackoverflow.com/questions/12905426/what-is-a-faster-alternative-to-pythons-http-server-or-simplehttpserver).

you're welcome to submit a PR though. I can't promise I'll take it but I will take a look

**Comment by baturinsky** [comment]
Hmm, you are right. But it's network, not extensions. It tries to load https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,500 even if offline, and gives up after 18s

**Comment by greggman** [comment]
What browser are you using? In Chrome with the network off it loads for me in 139ms. It doesn't wait for the font to download before showing the page.

<img width="680" alt="Screen Shot 2019-10-04 at 15 47 34" src="https://user-images.githubusercontent.com/234804/66186864-5ffb7300-e6be-11e9-9d57-100e5e83fdf3.png">

Even in Firefox it doens't wait for the fonts to download and only took 230ms

<img width="653" alt="Screen Shot 2019-10-04 at 15 50 01" src="https://user-images.githubusercontent.com/234804/66187000-b7014800-e6be-11e9-8f0a-2dac1262f418.png">

**Comment by baturinsky** [comment]
If network is off, browser probably just give up immediately. For me, googleapi just does not respond anything, not even 404, so it keeps trying. That's on latest Chrome and Firefox, but Opera somehow manages to load that font style without issues. Probably problem is with some extensions indeed...

**Comment by greggman** [comment]
Actually I tested something. If I configure my network to drop connections then I get the 20-40 second issue. No idea if you're running some kind of firewall or have configured your router to block google but if so you probably need to configure your router to reject rather than drop the connections. drop = don't repsond at all so the browser is left waiting wondering when the site is going to respon and finally timing out. reject = respond with 'unavailable' so the browser knows immediately there's nothing there.

Here's one example if you're running Pi-Hole

https://pi-hole.net/2018/02/02/why-some-pages-load-slow-when-using-pi-hole-and-how-to-fix-it/

**Comment by baturinsky** [comment]
I have tracked the source of issue, it was wrong ip of google fonts in Windows hosts file. Sorry for false positive.

Btw, I want to thank you for your lib and say that I like your coding style. I though I was only one that prefer vectors as arrays of numbers:)
