### ISSUE TITLE
Rendering objects using drawObjectList causes skybox to not be rendered

### ISSUE THREAD

**Issue by jparta** [greggman/twgl.js#229]
Making the following replacement in the last example of the Skybox tutorial results in the cube still rendering, but without the skybox. This is an unexpected interaction. See image below. It seems to have something to do with the setting of the 'a_position' buffer in drawObjectList -> setBuffersAndAttributes -> setAttributes, since skipping the setting of that buffer causes the skybox to appear.
https://webgl2fundamentals.org/webgl/lessons/webgl-skybox.html

```
  /*
    // draw the cube
    gl.depthFunc(gl.LESS);  // use the default depth test
    gl.useProgram(envmapProgramInfo.program);
    gl.bindVertexArray(cubeVAO);
    twgl.setUniforms(envmapProgramInfo, {
      u_world: worldMatrix,
      u_view: viewMatrix,
      u_projection: projectionMatrix,
      u_texture: texture,
      u_worldCameraPosition: cameraPosition,
    });
    twgl.drawBufferInfo(gl, cubeBufferInfo);
  */
    let objects = [
      {
        programInfo: envmapProgramInfo,
        bufferInfo: cubeBufferInfo,
        uniforms: {
          u_world: worldMatrix,
          u_view: viewMatrix,
          u_projection: projectionMatrix,
          u_texture: texture,
          u_worldCameraPosition: cameraPosition,
        },
      },
    ];
    twgl.drawObjectList(gl, objects);
```

![download](https://github.com/greggman/twgl.js/assets/25590558/5e4a57cb-295c-485a-947c-5d1b8a86db33)

**Comment by greggman** [comment]
It's because the sample is not using twgl to create vertex array infos. It's creating vertex arrays as their own object. So, when you call drawObjectList it's updating the previous vertex array's attributes since it has no knowledge of the vertex arrays

There is no easy way for twgl to handle this without imposing more structure. If you want it to work then call `twgl.createVertexArrayInfo` instead of `twgl.createVAOFromBufferInfo`

  const cubeVAI = twgl.createVertexArrayInfo(gl, [envmapProgramInfo], cubeBufferInfo);
  const quadVAI = twgl.createVertexArrayInfo(gl, [skyboxProgramInfo], quadBufferInfo);

And use those where you'd use a bufferInfo

https://jsgist.org/?src=caffb5445fa31fe48a6a2321fa25ce24

**Comment by jparta** [comment]
Great! That works.
Could some error be given if a VAO is used like this, to help people troubleshoot the issue?

**Comment by jparta** [comment]
Is that because checking for the mistake would take too much resources?

**Comment by jparta** [comment]
Okay, thanks for going above and beyond to explain the issue. Hope you have a good start to the week!
