### ISSUE TITLE
Framebuffer is still bound after calling "createFramebufferInfo"

### ISSUE THREAD

**Issue by mode777** [greggman/twgl.js#59]
I'm creating several framebuffers with createFramebufferInfo but I'm not doing anything with them yet.
However I noticed I have to explicitly unbind the framebuffer after this call, like this:
```js
       this.framebufferInfo = twgl.createFramebufferInfo(gl, [
            {
                attach: gl.COLOR_ATTACHMENT0,
                wrap: gl.REPEAT
            }
        ], this.width, this.height);
        twgl.bindFramebufferInfo(this.gl); // <--- unbind framebuffer
```
If I don't do this I cannot draw on the canvas. (tested with npm module and version 3.7.0).

Is this behaviour intentional?

**Comment by PrincessGod** [comment]
Hi there, you can use 
> twgl.bindFramebufferInfo(gl, null)

or just

> twgl.bindFramebufferInfo(gl)

May be these should be in documentation. 

Use `twgl.bindFramebufferInfo()` instand of `gl.bindFramebuffer()`.I think maybe this is what author mean.

**Comment by mode777** [comment]
Thank you but what I meant is: Is it intentional that the framebuffer is still bound after calling create....
Probably it's best to always call `twgl.bindFramebufferInfo(gl, null)` before drawing on the canvas.

**Comment by greggman** [comment]
It is semi-intentional. 

Most programs I've worked on have a render loop so they always set the framebuffer before they start rendering. Something like

      renderLoop {
           bind shadow frame buffer
           draw shadow data
           bind color frame buffer
           draw color data
           bind post processing buffer
           post process
           bind canvas
           draw post process result
      }

As such there's no need to unbind since the norm is to bind to whatever target before rendering to that target.  Textures are similar, twgl.createTexture does not unbind the texture for example.

twgl being just something to make webgl more terse isn't doing anything different than normal framebuffer creation in this case. You have to bind the framebuffer to create it so it does but it doesn't unbind it.

I'm open to arguments why it should be different but I guess it kind of seems like there's no plus or minus just opinion. If you're used to a normal render loop it doesn't matter which way it is. If you expect that just like normal WebGL after you create a framebuffer, since you had to bind it then it's still bound and you can render to it immediately then you'd want it the way it is now. If after you create it you immediately want to render to the canvas then you'd want it to unbind. I guess I feel like that last case is the exception though?

**Comment by mode777** [comment]
I haven't been aware this is the default behaviour for the create* function. I think if it is consistent, it should stay like this. 

That said, I think it should be noted in the docs. As this side-effect is IMO not apparent from the method name.
