### ISSUE TITLE
setting attributes to constant values

### ISSUE THREAD

**Issue by ajakaja** [greggman/twgl.js#85]
Hey,

I'm only learning WebGL this week so apologies if I've misunderstood something, but I haven't been able to find a way to do this in TWGL:

I have a shader which contains an attribute `a_color`. I'm using it for several figures, one of which has an array of colors which I've supplied using 

    let bufferInfo = twgl.createBufferInfoFromArrays(gl, {
	a_color: { numComponents: 4, data: colors, type: Uint8Array }
    });
    twgl.setBuffersAndAttributes(gl, programInfo, bufferInfo); 

But for the other I would like to just supply a constant color using 

    gl.disableVertexAttribArray(location);
    gl.vertexAttrib4f(a_color.location, 1.0, 0.5, 0.5, 1.0);

I don't see a way to do this in TWGL (looks like there are no calls to `vertexAttrib4f` in the codebase). 
Could it be possible to, say, supply a single value for the `a_color` instead of an array and get this behavior instead? Or is doing this a terrible idea for some other reason?

(I would be happy to try to implement this, but want to be sure of the approach first.)

**Comment by greggman** [comment]
You're right, there's no support for constant vertex attributes ATM

What should happen? Add `value` or `constant` to [`FullArraySpec`](http://twgljs.org/docs/module-twgl.html#.FullArraySpec) and to [`AttribInfo`](http://twgljs.org/docs/module-twgl.html#.AttribInfo)?

Then you could I guess do

```
const bufferInfo = twgl.createBufferInfoFromArrays(gl, {
    position: positions,
    color: { value: [1, 0, 0, 1], },
});
```

Single value seems problematic since at the moment it's checking for an array as in 

```
const bufferInfo = twgl.createBufferInfoFromArrays(gl, {
    position: [1,2,3],
});
```

make a buffer with 1,2,3 in it and it would seem strange if there was some arbitrary cutoff like less than 4 elements becomes a constant and > 4 elements becomes a buffer.

**Comment by ajakaja** [comment]
Perhaps the cutoff should be if `numComponents / data.length == 1`? That way you have to be explicitly setting a single value, if that's what really what you want.
Is there any case where setting one value with `gl. vertexAttrib[2/3/4]f()` has a different behavior than binding a one-element buffer? I'm not sure, but I'm new at this.

**Comment by greggman** [comment]
With `numComponents / data.length == 1` means that you'd have to put this

        color: { numComponents: 4, data: [1,0,0,1] },

vs just

        color: { value: [1,0,0,1] },
     
Since there is no need for `numComponents` when using `gl.vertexAttrib`. 

I threw together a proof of concept here
https://github.com/greggman/twgl.js/pull/86/files

I added 2 things, one is an easy way to reuse buffers.  You can pass a source `BufferInfo` into `twgl.createBufferInfoFromArrays` as the 3rd parameter. This lets you reuse buffers easier, just replacing one buffer for example

```
    const bufferInfo1 = twgl.createBufferInfoFromArrays(gl, {
      position: [...],
      normal: [...],
      texcoord: [...],
      color: [...],
    });

    // use the same position, normal, and texcoord buffers from bufferInfo1
    // but create a new color buffer
    const bufferInfo2 = twgl.createBufferInfoFromArrays(gl, {
      color: [...],
    }, bufferInfo1);
```

Then added support for using constants on attributes. An example

An example of using it is in there, the relevant part is

```
    const redBufferInfo = twgl.createBufferInfoFromArrays(gl, {
      position: [
        -1, -1, 0,
         1, -1, 0,
        -1,  1, 0,
         1,  1, 0,
      ],
      color: { value: [1, 0, 0, 1], },
      indices:  [
        0, 1, 2,
        2, 1, 3,
      ],
    });
    const greenBufferInfo = twgl.createBufferInfoFromArrays(gl, {
      color: { value: [0, 1, 0, 1], },
    }, redBufferInfo);
    const blueBufferInfo = twgl.createBufferInfoFromArrays(gl, {
      color: { value: [0, 0, 1, 1], },
    }, redBufferInfo);
    const yellowBufferInfo = twgl.createBufferInfoFromArrays(gl, {
      color: { value: [1, 1, 0, 1], },
    }, redBufferInfo);
```

**Comment by greggman** [comment]
This was added a while ago

live example: http://twgljs.org/examples/constant-attributes.html

source:  https://github.com/greggman/twgl.js/blob/master/examples/constant-attributes.html
