### ISSUE TITLE
Export texture formats

### ISSUE THREAD

**Issue by wdanilo** [greggman/twgl.js#92]
Hi! 
TWGL defines a lot of texture format constants, like `RGB32I` : 
https://github.com/greggman/twgl.js/blob/a37436b6334d5f489dc1407874631f23ecd743b5/src/textures.js#L109

It would be awesome if we could access them without the need to refer to browser-defined `WebGL2RenderingContext`. Would it be possible / in the spirit of this library to export them?

**Comment by greggman** [comment]
I'm curious. What would you gain?

You do

     twgl.createTexture(gl, { internalFormat: twgl.RG32I });

Or to not clutter the global namespace it would be

     twgl.createTexture(gl, { internalFormat: twgl.glConstants.RG32I });

Why is that better than

     twgl.createTexture(gl, { internalFormat: gl.RG32I });

**Comment by wdanilo** [comment]
Greg thanks for the fast answer! In such use case, it doesn't provide any value. However, I'm using it in a library, when `gl` context is not yet accessible. 

Howevevr, your argument regarding **all** constants is completely valid and you are right, if TWGL is not exporting them all (and of course it is not), it's better to keep them hidden than tell users to guess which are exported. In such case, it's just better to check if `WebGL2RenderingContext` exist and then just use it to get the constants.

**Comment by greggman** [comment]
FYI, if you really want to go crazy you can declare them yourself. I'm not suggesting you do this but if you run your code through a compressor like the Google Closure Compiler it can change all your constant usage to magic numbers. In other words will change 

      const foo = {
         R32F: 33326,
         RED: 6403,
         UNSIGNED_BYTE: 5121,
         TEXTURE_2D: 3553,
      };
      gl.texImage2D(foo.TEXTURE_2D, 0, foo.R32F, width, height, 0, foo.RED, foo.UNSIGNED_BYTE, null)

In to
         
      gl.texImage2D(3553, 0, 33326, width, height, 0, 6403, 5121, null)

You can see that google maps does this by inspecting the google maps code in the debugger. They declare all the WebGL constants [here](https://github.com/google/closure-library/blob/master/closure/goog/webgl/webgl.js)

**Comment by zorro-fr24** [comment]
`const foo = {
     R32F: 33326,
     RED: 6403,
     UNSIGNED_BYTE: 5121,
     TEXTURE_2D: 3553,
  };`

I suspect this may not be optimised in that fashion, since properties of a constant object are still actually mutable in javascript.

This is probably why google declares each constant individually.

**Comment by zorro-fr24** [comment]
Note: there are a few gl constant libraries in npm which you can use if you really want this feature ( I saw at least one with both webgl1 and 2 defs, and it said it supported tree-shaking, which should cut down on unnecessary bloat.

**Comment by greggman** [comment]
it optimizes just fine. Google does it the other way because they want to add types to each value and their old system needs a  comment per constant to check types

[Example](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconst%2520gl%2520%253D%2520document.createElement(%2522canvas%2522).getContext(%2522webgl%2522)%253B%250Aconst%2520foo%2520%253D%2520%257B%250A%2520%2520%2520%2520%2520R32F%253A%252033326%252C%250A%2520%2520%2520%2520%2520RED%253A%25206403%252C%250A%2520%2520%2520%2520%2520UNSIGNED_BYTE%253A%25205121%252C%250A%2520%2520%2520%2520%2520TEXTURE_2D%253A%25203553%252C%250A%2520%2520%257D%253B%250Agl.texImage2D(foo.TEXTURE_2D%252C%25200%252C%2520foo.R32F%252C%2520width%252C%2520height%252C%25200%252C%2520foo.RED%252C%2520foo.UNSIGNED_BYTE%252C%2520null)%250A%250A)

Check *Advanced*

Result:

```
document.createElement("canvas").getContext("webgl").texImage2D(3553,0,33326,width,height,0,6403,5121,null);
```

**Comment by zorro-fr24** [comment]
ah nice.
Closure is much more clever than uglify. It even handles it if I re-assign a property - by extracting it into a variable first.

However, if you aren't using closure, eg transpiling via babel then using a constant folding plugin works for individual constants, but not for objects

**Comment by greggman** [comment]
There's no difference between

```
const foo = {}
foo.R32F = 33326;
foo.RED = 6403;
foo.UNSIGNED_BYTE = 5121;
foo.TEXTURE_2D = 3553;
```

and

```
const foo = {
     R32F: 33326,
     RED: 6403,
     UNSIGNED_BYTE: 5121,
     TEXTURE_2D: 3553,
};
```

In both cases `foo` is a reference to an object that can be modified. If Uglify can handle the first and not the second it's a bug as the 2 are indistinguishable.
